### Some data clean up that's necessary for our project

In [1]:
import pandas as pd
import numpy as np

In [2]:
spotify = pd.read_csv('/Users/michellehewson/Desktop/Harvard/CS171/FinalProject/cs171_finalproject/data/spotify_top_charts_22.csv')  
tiktok = pd.read_csv('/Users/michellehewson/Desktop/Harvard/CS171/FinalProject/cs171_finalproject/data/TikTok_songs_2022 2.csv')

In [3]:
# Checking out our data
spotify.head()

,uri,artist_names,track_name,peak_rank,weeks_on_chart,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,tempo,time_signature,duration_ms
0,spotify:track:02MWAaffLxlfxAUY7c5dvx,Glass Animals,Heat Waves,1,65,0.761,0.525,11,-6.900,1,0.0944,0.4400,0.000007,0.0921,80.870,4,238805
1,spotify:track:5PjdY0CKGZdEuoNab3yDmX,"The Kid LAROI, Justin Bieber",STAY (with Justin Bieber),1,37,0.591,0.764,1,-5.484,1,0.0483,0.0383,0.000000,0.1030,169.928,4,141806
2,spotify:track:3IAfUEeaXRX9s9UdKOJrFI,Anitta,Envolver,3,3,0.812,0.736,4,-5.421,0,0.0833,0.1520,0.002540,0.0914,91.993,4,193806
3,spotify:track:1HhNoOuqm1a5MXYEgAFl8o,"Imagine Dragons, JID, Arcane, League of Legends",Enemy (with JID) - from the series Arcane Leag...,3,21,0.728,0.783,11,-4.424,0,0.2660,0.2370,0.000000,0.4340,77.011,4,173381
4,spotify:track:4fouWK6XVHhzl78KzQ1UjL,GAYLE,abcdefu,1,19,0.695,0.540,4,-5.692,1,0.0493,0.2990,0.000000,0.3670,121.932,4,168602

In [4]:
# Need to clean up the names of tracks (the syntax between both of the datasets is not the same)
# TikTok dataset has a lot of "SONG (feat. artist2, artist3)"
# Spotify dataset has "SONG" and then the artist names in the artist_names column
# For simplicity's sake, we'll just count the first artist listed as the owner of the song and ignore the features

spotify['old_track_name'] = spotify['track_name']
spotify['track_name'] = spotify['track_name'].str.split('(', n=1).str[0]
spotify['track_name'] = spotify['track_name'].str.split('-', n=1).str[0]

tiktok['old_track_name'] = tiktok['track_name']
tiktok['track_name'] = tiktok['track_name'].str.split('(', n=1).str[0]
tiktok['track_name'] = tiktok['track_name'].str.split('-', n=1).str[0]

In [5]:
spotify['old_artist_names'] = spotify['artist_names']
spotify['artist_names'] = spotify['artist_names'].str.split(',', n=1).str[0]
spotify = spotify.rename(columns={'artist_names': 'artist_name'})
spotify.head()

,uri,artist_name,track_name,peak_rank,weeks_on_chart,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,tempo,time_signature,duration_ms,old_track_name,old_artist_names
0,spotify:track:02MWAaffLxlfxAUY7c5dvx,Glass Animals,Heat Waves,1,65,0.761,0.525,11,-6.900,1,0.0944,0.4400,0.000007,0.0921,80.870,4,238805,Heat Waves,Glass Animals
1,spotify:track:5PjdY0CKGZdEuoNab3yDmX,The Kid LAROI,STAY,1,37,0.591,0.764,1,-5.484,1,0.0483,0.0383,0.000000,0.1030,169.928,4,141806,STAY (with Justin Bieber),"The Kid LAROI, Justin Bieber"
2,spotify:track:3IAfUEeaXRX9s9UdKOJrFI,Anitta,Envolver,3,3,0.812,0.736,4,-5.421,0,0.0833,0.1520,0.002540,0.0914,91.993,4,193806,Envolver,Anitta
3,spotify:track:1HhNoOuqm1a5MXYEgAFl8o,Imagine Dragons,Enemy,3,21,0.728,0.783,11,-4.424,0,0.2660,0.2370,0.000000,0.4340,77.011,4,173381,Enemy (with JID) - from the series Arcane Leag...,"Imagine Dragons, JID, Arcane, League of Legends"
4,spotify:track:4fouWK6XVHhzl78KzQ1UjL,GAYLE,abcdefu,1,19,0.695,0.540,4,-5.692,1,0.0493,0.2990,0.000000,0.3670,121.932,4,168602,abcdefu,GAYLE

In [6]:
# all of the songs that appear in both datasets (so they're a top song on tiktok AND spotify)
merged_df = pd.merge(tiktok, spotify, on='track_name', how='inner')

In [7]:
# make some new CSVs
#spotify.to_csv('spotify_clean.csv', index=False)
#tiktok.to_csv('tiktok_clean.csv', index=False)
#merged_df.to_csv('tiktok_spotify_merged.csv', index=False)

In [8]:
# Counting how many songs an artist has (they're the first one listed) in the top spotify charts
spotify_artist_counts = spotify['artist_name'].value_counts().reset_index()
spotify_artist_counts.columns = ['artist', 'count']

spotify_artist_counts = pd.DataFrame(spotify_artist_counts)
spotify_artist_counts.head()

           artist  count
0       Bad Bunny     29
1      The Weeknd     27
2  Kendrick Lamar     21
3    Harry Styles     18
4           Drake     18

In [9]:
tiktok_artist_counts = tiktok['artist_name'].value_counts().reset_index()
tiktok_artist_counts.columns = ['artist', 'count']
tiktok_artist_counts.head()

      artist  count
0   Doja Cat      8
1     Coopex      6
2  Dame Dame      5
3  Lil Nas X      4
4      Farux      4

In [10]:
#spotify_artist_counts.to_csv('spotify_artist_counts.csv', index=False)
#tiktok_artist_counts.to_csv('tiktok_artist_counts.csv', index=False)

In [ ]:
# creating specific dataframe for key information in the tiktok and spotify datasets

In [19]:
num_tiktok_songs = len(tiktok)
num_spotify_songs = len(spotify)

In [34]:
tiktok_keys = tiktok['key'].value_counts()
tiktok_keys = pd.DataFrame(tiktok_keys).reset_index()
tiktok_keys['percentage'] = round((tiktok_keys['count'] / num_tiktok_songs),3) * 100

tiktok_keys

    key  count  percentage
0    11     33        12.5
1     1     30        11.4
2     6     27        10.3
3     8     27        10.3
4     0     25         9.5
5    10     23         8.7
6     4     23         8.7
7     9     19         7.2
8     5     18         6.8
9     7     18         6.8
10    2     12         4.6
11    3      8         3.0

In [35]:
spotify_keys = spotify['key'].value_counts()
spotify_keys = pd.DataFrame(spotify_keys).reset_index()
spotify_keys['percentage'] = round((spotify_keys['count'] / num_spotify_songs),3) * 100

spotify_keys

    key  count  percentage
0     1    104        16.1
1     8     65        10.1
2     0     63         9.8
3     2     56         8.7
4     5     55         8.5
5    11     54         8.4
6     7     52         8.0
7     4     45         7.0
8    10     45         7.0
9     9     42         6.5
10    6     38         5.9
11    3     27         4.2

In [36]:
# make some new CSVs
#spotify_keys.to_csv('spotify_keys.csv', index=False)
#tiktok_keys.to_csv('tiktok_keys.csv', index=False)